main: me.saiintbrisson.minecraft.InventoryFramework
name: InventoryFramework
version: @version@
authors: [SaiintBrisson, DevNatan, sasuked]
website: https://github.com/saiintbrisson/inventory-framework
description: Bukkit Inventory API framework